FROM golang:alpine

RUN apk update && apk add git

ENV PORT=7072
ENV DB_USER="sperma"
ENV DB_PASS="asdQWE123!@#"
ENV DB_HOST="165.22.242.64"
ENV DB_PORT="3306"
ENV DB_NAME="db_tot"
ENV DB_DRIVER="mysql"
ENV DB_REDIS_HOST="128.199.124.131:6379"
ENV DB_REDIS_PASSWORD="asdQWE123!@#"
ENV DB_REDIS_NAME="0"
ENV JWT_SECRET_KEY="secrettotobackend"
ENV JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT=1440

WORKDIR /app

COPY . .

RUN go mod tidy
RUN go build -o binary

ENTRYPOINT [ "./binary" ]